### ISSUE TITLE
Input anf pickle files are missing

### ISSUE THREAD

**Issue by hemesh0204** [ZeroNP/VyakaranBackend#1]
While running the project, we were not able to load the dataset and the pickle file as they are inside the drive and it is not uploaded in the Github. so it will be really helpful if you could share the drive link.

**Comment by nikam-shreyas** [comment]
Hey @Hemesh0204,
Here is the drive link:
https://drive.google.com/drive/folders/1lxH5wE0re3HEM2iJW051haCuwH9MMQvF?usp=share_link
